### ISSUE TITLE
Breadcrumb broken in some 2.x pages

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2527] opened 2015-03-23 14:14 UTC
E.g. http://book.cakephp.org/2.0/en/models/behaviors.html

    Core Libraries General Purpose Events System 

instead of

    Model

**Comment by markstory** [comment] 2015-03-23 14:47
This is probably caused by our TOC including files more than once.

**Comment by cake17** [comment] 2015-09-11 08:54
I was trying to correct this issue, but I think the way the menu is build causes the issue.

The `behaviors` section is at 2 places : under `/models` and under `/core-libraries`.
Maybe we can get inspired by the CakePHP 3 docs.  Meaning, we just let:
- behaviors only under `models`
- components only under `controllers`
- helpers only under `views`

Moreover, all files under `core-utility-libraries` could go under `core-libraries`.
What do you think of it?

**Comment by cake17** [comment] 2015-09-11 08:59
![capture d ecran 2015-09-11 a 10 55 01](https://cloud.githubusercontent.com/assets/1652972/9810882/f86d943e-5873-11e5-906c-c19cb8e24bae.png)
![capture d ecran 2015-09-11 a 10 55 09](https://cloud.githubusercontent.com/assets/1652972/9810883/f8722198-5873-11e5-984e-38b43392940e.png)
![capture d ecran 2015-09-11 a 10 55 15](https://cloud.githubusercontent.com/assets/1652972/9810885/f87a1c22-5873-11e5-9111-233a2567a779.png)
![capture d ecran 2015-09-11 a 10 55 42](https://cloud.githubusercontent.com/assets/1652972/9810884/f87564de-5873-11e5-9926-59f63c6db63b.png)

**Comment by markstory** [comment] 2015-09-11 21:28
Pull request open now.

**Comment by cake17** [comment] 2016-02-01 10:17
PR could not be merged. No good solution has been found yet. I reopen this

**Comment by dereuromark** [comment] 2016-10-15 22:27
For the new layout this doesn't seem to be relevant anymore.

**Closed** 2016-10-16 12:30 UTC
Labels: defect
