### ISSUE TITLE
Incorrect TOC for Helpers

### ISSUE THREAD

**Issue by ritesh-pandey** [cakephp/docs#4286] opened 2016-08-31 17:50 UTC
Applicable for CakePHP < 3.0

Go to any Core Helper e.g. `CacheHelper` http://book.cakephp.org/2.0/en/core-libraries/helpers/cache.html

The TOC on LHS is showing that you are at `Core Libraries` > `General Purpose`
It should instead have been `Core Libraries` > `Helpers` > `CacheHelper`

Attached screenshot for reference.
![screenshot from 2016-08-31 23-21-08](https://cloud.githubusercontent.com/assets/1433681/18140087/a18096b4-6fd1-11e6-9762-d7065ab72f7f.png)

![screenshot from 2016-08-31 22-58-50](https://cloud.githubusercontent.com/assets/1433681/18140040/75d51544-6fd1-11e6-84e4-749116ace53f.png)

**Comment by markstory** [comment] 2016-08-31 19:20
Duplicate of #2527

**Closed by markstory** 2016-08-31 19:20 UTC
