### ISSUE TITLE
Quick Start Guide Mysql Table syntax

### ISSUE THREAD

**Issue by vontani** [cakephp/docs#7315] opened 2022-02-04 20:29 UTC
**Issue Description**

Someone should update the quick start guide so freaks like me can smoothly start learning using cake !

please check the mysql section and compare syntax to 8.0 , that did not work, needs some modifications.

thanks

---

**Do you want to address this issue?**

**Comment by ndm2** [comment] 2022-02-05 01:02
Can you provide some more details as to what problem exactly you're experiencing (any errors?), and the specific MySQL version you are using?

**Comment by vontani** [comment] 2022-02-05 07:13
Sure, 
just trying to execute your quick start guide sql code and got an syntax error 

*******
failed : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
******

Machine:
MySQL version 8.0.28-0 on an ubuntu0.20.04.3 headless 

Regards

**Comment by ndm2** [comment] 2022-02-05 10:29
I can't reproduce any problems using 8.0.28 from https://hub.docker.com/_/mysql.

Can you please post the complete error message, that is including the SQL snippet after "_use near_", and also include the exact SQL that you are trying execute?

**Comment by othercorey** [comment] 2022-02-05 11:27
Please show the sql you're executing. This isn't enough information.

**Comment by vontani** [comment] 2022-02-05 11:47
dear,

I'm on phpcacke starting with your "quick start guide" on my ubuntu headless server powered by virtualmin for better management.

i execute the sql table create code u provided by copy - past.

here the fully output:
*****
Failed to execute SQL : SQL CREATE TABLE users ( id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, created DATETIME, modified DATETIME ); CREATE TABLE articles ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(191) NOT NULL, body TEXT, published BOOLEAN DEFAULT FALSE, created DATETIME, modified DATETIME, UNIQUE KEY (slug), FOREIGN KEY user_key (user_id) REFERENCES users(id) ) CHARSET=utf8mb4; CREATE TABLE tags ( id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(191), created DATETIME, modified DATETIME, UNIQUE KEY (title) ) CHARSET=utf8mb4; CREATE TABLE articles_tags ( article_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (article_id, tag_id), FOREIGN KEY tag_key(tag_id) REFERENCES tags(id), FOREIGN KEY article_key(article_id) REFERENCES articles(id) ); INSERT INTO users (email, password, created, modified) VALUES ('cakephp@example.com', 'secret', NOW(), NOW()); INSERT INTO articles (user_id, title, slug, body, published, created, modified) VALUES (1, 'First Post', 'first-post', 'This is the first post.', 1, NOW(), NOW()); failed : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE articles ( id INT AUTO_INCREMENT PRIMARY KEY, user_id INT N' at line 1
*****

hope that helps ! 

BTW, i did an syntax check and got error on line 9 consulting this page (https://en.rakko.tools/tools/36/) 

Regards

**Comment by vontani** [comment] 2022-02-05 12:49
Dear, 
using terminal i can fine execute the sql syntax and all tables are created but local at a gui window wont work, so i conclude that cake is an Terminal only installer.

**Comment by LordSimal** [comment] 2022-02-05 13:03
I also wasn't able to reproduce that error in PHPMyAdmin.

The only thing I can imagine is some weird copy/paste encoding issue where your GUI program changed the single quotes `'` to something different it doesn't understand but there is definitely nothing wrong with the SQL given in the Quick Start guide.

**Comment by saeideng** [comment] 2022-02-05 17:36
I tested on mysql 8, no problem on queries
also mentioned site can not analyze  queries at same time , so only analyze it separately
we can close this issue as it works as expected

**Comment by saeideng** [comment] 2022-02-05 17:41
if you need any help you can ask it in support channels

**Closed as completed** 2022-02-05 18:12 UTC
